<!-- #include virtual="/layout/_top.asp" -->
<%
	Set objConn = Server.CreateObject("ADODB.Connection")
	objConn.Open "PROVIDER=SQLOLEDB;DATA SOURCE=209.133.228.174;UID=msuboutreachnet;PWD=3a4d7a2m;DATABASE=msuboutreachnet;"
	Set objComm = Server.CreateObject("ADODB.Command")
	Set objComm.ActiveConnection = objConn
	objComm.CommandText = "msuboutreachnet.prc_event_upd"
	objComm.CommandType = &H0004
		
	objComm.Parameters.Append objComm.CreateParameter("@RETURN_VALUE", 3,4,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_process_type", 200,1,5)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_id", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_title", 200,1,255)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_crn", 200,1,10)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_rubric", 200,1,10)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_number", 200,1,10)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_section", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_quarter", 200,1,5)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_semester", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_year", 200,1,4)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_application_date", 200,1,100)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_status", 200,1,2)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_grading", 200,1,20)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_index", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_detail_code", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_type", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_sponsorship", 200,1,2)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_sponsor_information", 200,1,2000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_enrollment_actual", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_enrollment_estimated", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_enrollment_minimum", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_enrollment_maximum", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_days", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_participant_days", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_outcomes_comments", 200,1,2000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_remarks", 200,1,4000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_description", 200,1,4000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_target_audience", 200,1,2000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_evaluation_of_work", 200,1,2000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_required_materials", 200,1,2000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_post_course_work", 200,1,2000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_caf_comments", 200,1,2000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_selected_ind", 200,1,1)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_grades_to_inst", 135,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_evals_to_inst", 135,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_grades_from_inst", 135,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_grades_to_reg", 135,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_evals_from_inst", 135,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_eval_delivery_method", 200,1,10)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_budget_notes", 200,1,2000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_open_room_time", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_open_room_personnel_id", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_lock_room_time", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_lock_room_personnel_id", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_room_setup_time", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_room_setup_personnel_id", 3,1,0)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_catering_set_time", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_outside_catering", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_outside_catering_contact", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_outside_phone_number", 200,1,50)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_event_repetition", 200,1,10)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_eval_complete_ind", 200,1,10)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_lgstc_signage_reqd_ind", 200,1,1)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_room_setup_day_ind", 200,1,5)	
	objComm.Parameters.Append objComm.CreateParameter("@p_in_catering_needs", 200,1,2000,Null)	
	objComm.Parameters.Append objComm.CreateParameter("@p_in_room_setup_notes", 200,1,2000,Null)	
	objComm.Parameters.Append objComm.CreateParameter("@p_in_catering_personnel_id", 3,1,0,Null)	
	objComm.Parameters.Append objComm.CreateParameter("@p_in_caterer_notes", 200,1,8000,Null)	
	'Field added 08/03/2008
	objComm.Parameters.Append objComm.CreateParameter("@p_in_inv_comp_ind", 200,1,1,Null)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_variable_string", 200,3,2000)
	objComm.Parameters.Append objComm.CreateParameter("@p_in_log_user_id", 3,1,0)

	objComm("@p_in_process_type") 				= "RMOVE"
	objComm("@p_in_event_id") 					= validate_field(Request.QueryString("event_id"),"pl")
	objComm("@p_in_event_title") 				= Null
	objComm("@p_in_event_crn") 					= Null
	objComm("@p_in_event_rubric") 				= Null
	objComm("@p_in_event_number")				= Null
	objComm("@p_in_event_section") 				= Null
	objComm("@p_in_event_quarter") 				= Null
	objComm("@p_in_event_semester") 			= Null
	objComm("@p_in_event_year") 				= Null
	objComm("@p_in_application_date") 			= Null
	objComm("@p_in_event_status") 				= Null
	objComm("@p_in_event_grading") 				= Null
	objComm("@p_in_event_index") 				= Null
	objComm("@p_in_detail_code") 				= Null
	objComm("@p_in_event_type") 				= Null
	objComm("@p_in_event_sponsorship") 			= Null
	objComm("@p_in_sponsor_information") 		= Null
	objComm("@p_in_enrollment_actual")			= Null
	objComm("@p_in_enrollment_estimated")		= Null
	objComm("@p_in_enrollment_minimum") 		= Null
	objComm("@p_in_enrollment_maximum") 		= Null
	objComm("@p_in_event_days") 				= Null
	objComm("@p_in_participant_days") 			= Null
	objComm("@p_in_outcomes_comments") 			= Null
	objComm("@p_in_event_remarks") 				= Null
	objComm("@p_in_event_description") 			= Null
	objComm("@p_in_target_audience")			= Null
	objComm("@p_in_evaluation_of_work") 		= Null
	objComm("@p_in_required_materials")			= Null
	objComm("@p_in_post_course_work") 			= Null
	objComm("@p_in_caf_comments") 				= Null
	objComm("@p_in_selected_ind") 				= Null
	objComm("@p_in_grades_to_inst") 			= Null
	objComm("@p_in_evals_to_inst") 				= Null
	objComm("@p_in_grades_from_inst") 			= Null
	objComm("@p_in_grades_to_reg") 				= Null
	objComm("@p_in_evals_from_inst") 			= Null
	objComm("@p_in_eval_delivery_method") 		= Null
	objComm("@p_in_budget_notes") 				= Null
	objComm("@p_in_open_room_time") 			= Null
	objComm("@p_in_open_room_personnel_id") 	= Null
	objComm("@p_in_lock_room_time") 			= Null
	objComm("@p_in_lock_room_personnel_id") 	= Null
	objComm("@p_in_room_setup_time") 			= Null
	objComm("@p_in_room_setup_personnel_id") 	= Null
	objComm("@p_in_catering_set_time") 			= Null
	objComm("@p_in_outside_catering") 			= Null
	objComm("@p_in_outside_catering_contact") 	= Null
	objComm("@p_in_outside_phone_number") 		= Null
	objComm("@p_in_event_repetition") 			= Null
	objComm("@p_in_eval_complete_ind") 			= Null
	objComm("@p_in_lgstc_signage_reqd_ind") 	= Null
	objComm("@p_in_room_setup_day_ind") 		= Null
	objComm("@p_in_variable_string") 			= Null
	objComm("@p_in_log_user_id") 				= Session("user_id")
  	
	objComm.Execute
	Session("Event removed successfully.")
	Response.Redirect("/index.asp")
%>
<!-- #include virtual="/layout/_bottom.asp" -->